// 佛光寺东大殿外檐柱头铺作·七铺作双杪双下昂·偷心造（自下而上，共 15 件）
// 尺寸依《营造法式》分°：斗口=10分，材广=15分，足材广=21分。
// 主轴出跳「偷心」——外跳跳头不施横栱；横栱只在泥道一列与最上令栱处。
// 每出一跳，跳头开斗口纳一交互斗，交互斗再承上一层的栱/昂——交互斗是独立构件，各占一步。

export const REQUIRED_FIELDS = [
  'id', 'name', 'term', 'pinyin', 'dims',
  'juansha', 'layer', 'parents', 'role', 'desc', 'trivia', 'hasForceAnim',
]

export const PARTS = [
  {
    id: 'ludou', name: '栌斗', term: '栌斗', pinyin: 'lúdǒu',
    dims: { fang: 32, height: 20, ear: 8, ping: 4, xie: 8, kouWidth: 10 },
    juansha: null, layer: 0, parents: [],
    role: '全朵之基，坐于柱头，承托上部所有出跳与横栱，最终将屋檐之力汇聚落柱。',
    desc: '栌斗是斗栱最下、最大的坐斗，方三十二分、高二十分，上开十字口以纳第一跳华栱与泥道栱。斗身自上而下分耳、平、欹三段。',
    trivia: '佛光寺东大殿的栌斗尺度雄大，是判定其为唐构的重要依据之一——斗口越大，用材等级越高。',
    hasForceAnim: true,
  },
  {
    id: 'huagong-1', name: '华栱·第一杪', term: '华栱', pinyin: 'huágǒng',
    dims: { length: 72, caiGuang: 21, houDou: 10, chuTiao: 30, lap: { side: 'top', width: 10, depth: 10 } },
    juansha: 4, layer: 1, parents: ['ludou'],
    role: '自栌斗十字口纵向出第一跳（杪），向外悬挑并承上层。',
    desc: '华栱是横向出跳的栱，足材造，广二十一分、厚十分，栱头卷杀四瓣。佛光寺此跳为「偷心」——跳头不施横栱，唯见华栱层层挑出，气魄雄浑。',
    trivia: '「偷心造」是唐及辽构的典型手法，宋《营造法式》以后多改「计心」，故一眼「偷心」便知年代古老。',
    hasForceAnim: true,
  },
  {
    id: 'nidaogong', name: '泥道栱', term: '泥道栱', pinyin: 'nídàogǒng',
    dims: { length: 62, caiGuang: 15, houDou: 10, lap: { side: 'bottom', width: 10, depth: 10 } },
    juansha: 4, layer: 2, parents: ['ludou'],
    role: '坐于栌斗、沿墙身（进深）方向横置，与第一跳华栱在栌斗口内十字相交，稳住栌斗一列。',
    desc: '泥道栱是栌斗上沿墙面横向的栱，单材造，与纵向的华栱十字相交同纳于栌斗口。它属「泥道」一列，不随出跳外挑，只在原地横向铺展、承其上的柱头枋。',
    trivia: '华栱出跳、泥道栱横陈，一纵一横同坐栌斗口——这「十字栱」正是斗栱由一点向四方分力的起点。',
    hasForceAnim: false,
  },
  {
    id: 'sandou-1', name: '散斗·泥道右', term: '散斗', pinyin: 'sǎndǒu',
    dims: { fang: 16, height: 10, ear: 4, ping: 2, xie: 4, kouWidth: 6, singleKou: true },
    juansha: null, layer: 2.3, parents: ['nidaogong'],
    role: '坐于泥道栱右端栱头，与左端散斗一同承托其上的柱头枋。',
    desc: '散斗是置于栱两端的小斗，斗口向上。它落在泥道栱的栱头上，托起沿墙通长的柱头枋——枋不落斗口，而是搁在这一对散斗上。',
    trivia: '散斗只承一头、不出跳，是斗中最"素"的一种；栱端置散斗、栱心置交互斗，是辨识斗位的基本规律。',
    hasForceAnim: false,
  },
  {
    id: 'sandou-2', name: '散斗·泥道左', term: '散斗', pinyin: 'sǎndǒu',
    dims: { fang: 16, height: 10, ear: 4, ping: 2, xie: 4, kouWidth: 6, singleKou: true },
    juansha: null, layer: 2.6, parents: ['nidaogong'],
    role: '坐于泥道栱左端栱头，与右端散斗一同承托其上的柱头枋。',
    desc: '散斗对称置于泥道栱两端，斗口向上，共承柱头枋。左右两散斗把枋的重量分落到泥道栱的两个栱头上。',
    trivia: '一栱两端各一散斗、栱心一斗，合称"一栱三斗"，是横栱之上标准的坐斗布置。',
    hasForceAnim: false,
  },
  {
    id: 'zhutoufang', name: '柱头枋', term: '柱头枋', pinyin: 'zhùtóufāng',
    dims: { length: 120, caiGuang: 15, houDou: 10 },
    juansha: null, layer: 3, parents: ['sandou-1', 'sandou-2'],
    role: '压在泥道栱之上、沿墙面通长的枋木，把相邻各朵斗栱在墙身方向连成一气。',
    desc: '柱头枋是沿柱头通长的横木，压在泥道栱两端的散斗上，沿墙面（面阔方向）贯通。它把一柱之上的这朵与相邻各朵在墙身方向联成整体，是铺作层横向的联系构件。',
    trivia: '柱头枋沿柱头一线通长，故相邻斗栱虽各自出跳，墙身方向却由这道枋连成一气——铺作层因此既是承檐的托架，也是联络全屋的水平箍。',
    hasForceAnim: false,
  },
  {
    id: 'jiaohudou-1', name: '交互斗·承二杪', term: '交互斗', pinyin: 'jiāohùdǒu',
    dims: { fang: 18, height: 10, ear: 4, ping: 2, xie: 4, kouWidth: 8 },
    juansha: null, layer: 4, parents: ['huagong-1'],
    role: '坐于第一杪华栱跳头，斗口纳住其上的第二杪华栱，是这一跳与上一层之间的过渡承托。',
    desc: '交互斗是置于跳头、承接上下两层出跳构件的小斗。它落在第一杪华栱挑出的跳头斗口内，斗身开口再朝上纳住第二杪华栱，使上下两杪不是悬空相叠而是层层坐实。',
    trivia: '交互斗虽小，却是斗栱"逐跳坐斗"的关节——正因每跳跳头都有它承接，出跳才能一层层稳稳叠高而不散。',
    hasForceAnim: false,
  },
  {
    id: 'huagong-2', name: '华栱·第二杪', term: '华栱', pinyin: 'huágǒng',
    dims: { length: 72, caiGuang: 21, houDou: 10, chuTiao: 30, lap: { side: 'bottom', width: 10, depth: 7, at: -4 } },
    juansha: 4, layer: 5, parents: ['jiaohudou-1'],
    role: '出第二跳（杪），跳头置交互斗以承其上下昂。',
    desc: '第二跳华栱之上置交互斗，承接第一下昂。至此出跳两次，皆为杪（华栱），跳头仍偷心不施横栱。',
    trivia: '「双杪」即连出两跳华栱；佛光寺再叠「双下昂」，合为「双杪双下昂」七铺作，是唐代最高等级的铺作之一。',
    hasForceAnim: false,
  },
  {
    id: 'jiaohudou-2', name: '交互斗·承一昂', term: '交互斗', pinyin: 'jiāohùdǒu',
    dims: { fang: 18, height: 10, ear: 4, ping: 2, xie: 4, kouWidth: 8 },
    juansha: null, layer: 6, parents: ['huagong-2'],
    role: '坐于第二杪华栱跳头，承接其上斜置的第一下昂，是由「杪」转「昂」的过渡承托。',
    desc: '此交互斗落在第二杪华栱的跳头斗口内，斗口朝上纳住斜伸的第一下昂昂身。斗栱至此由横挑的华栱转为斜挑的下昂，全靠这颗小斗把两种构件接续起来。',
    trivia: '从华栱到下昂的换手处最见匠心——交互斗既要坐平华栱跳头、托住斜下的昂，又要在斗口十字方向纳住计心的瓜子栱。',
    hasForceAnim: false,
  },
  {
    id: 'guazigong', name: '瓜子栱', term: '瓜子栱', pinyin: 'guāzigǒng',
    dims: { length: 62, caiGuang: 15, houDou: 10 },
    juansha: 4, layer: 6.1, parents: ['jiaohudou-2'],
    role: '第二跳跳头的横栱，与第一下昂在交互斗口十字相交，是这一跳「计心」的起手。',
    desc: '瓜子栱是最短的横栱，横陈于第二杪华栱跳头的交互斗上，与斜出的下昂十字相交。此跳施横栱即为「计心」——佛光寺东大殿正是一、三跳偷心，二、四跳计心的「隔跳偷心造」。',
    trivia: '梁思成实测东大殿逐跳记：一跳偷心、二跳施瓜子栱慢栱承罗汉枋、三跳偷心、四跳令栱耍头相交——所以它并非全偷心，而是隔跳偷心。',
    hasForceAnim: false,
  },
  {
    id: 'sandou-5', name: '散斗·瓜子右', term: '散斗', pinyin: 'sǎndǒu',
    dims: { fang: 16, height: 10, ear: 4, ping: 2, xie: 4, kouWidth: 6, singleKou: true },
    juansha: null, layer: 6.2, parents: ['guazigong'],
    role: '坐于瓜子栱右端栱头，与左端散斗一同承其上的慢栱。',
    desc: '散斗置于瓜子栱右端，斗口向上，承接上一层更长的慢栱——瓜子栱与慢栱上下相叠，即「重栱」计心之制。',
    trivia: '瓜子栱短、慢栱长，二者相叠为重栱；栱端皆以散斗承接，是计心造层层出横栱的标准接法。',
    hasForceAnim: false,
  },
  {
    id: 'sandou-6', name: '散斗·瓜子左', term: '散斗', pinyin: 'sǎndǒu',
    dims: { fang: 16, height: 10, ear: 4, ping: 2, xie: 4, kouWidth: 6, singleKou: true },
    juansha: null, layer: 6.3, parents: ['guazigong'],
    role: '坐于瓜子栱左端栱头，与右端散斗一同承其上的慢栱。',
    desc: '散斗对称置于瓜子栱两端，斗口向上，共承慢栱。左右散斗把慢栱的重量分落到瓜子栱两端。',
    trivia: '瓜子栱两端两散斗，与令栱、泥道栱同为一栱两端各一斗之制——横栱之上标准的坐斗布置。',
    hasForceAnim: false,
  },
  {
    id: 'mangong', name: '慢栱', term: '慢栱', pinyin: 'màngǒng',
    dims: { length: 92, caiGuang: 15, houDou: 10 },
    juansha: 4, layer: 6.4, parents: ['sandou-5', 'sandou-6'],
    role: '叠于瓜子栱之上的长横栱，承其上通长的罗汉枋，与瓜子栱合为一组重栱。',
    desc: '慢栱是较瓜子栱更长的横栱，坐于瓜子栱两端散斗上，二者上下相叠为「重栱」。慢栱之上再置散斗，承通长的罗汉枋。',
    trivia: '瓜子栱—慢栱—罗汉枋这一组「重栱计心」，正是隔跳偷心里那一跳「计心」的实体；有它，第二跳才不同于一、三跳的偷心。',
    hasForceAnim: false,
  },
  {
    id: 'sandou-7', name: '散斗·慢栱右', term: '散斗', pinyin: 'sǎndǒu',
    dims: { fang: 16, height: 10, ear: 4, ping: 2, xie: 4, kouWidth: 6, singleKou: true },
    juansha: null, layer: 6.5, parents: ['mangong'],
    role: '坐于慢栱右端栱头，与左端散斗一同承其上的罗汉枋。',
    desc: '散斗置于慢栱右端，斗口向上，承接通长的罗汉枋——罗汉枋沿墙面横陈，把相邻各朵在此跳连成一气。',
    trivia: '罗汉枋是计心横栱之上的联系枋，位在柱头枋之外一跳；其名「罗汉」，为营造法式对这道枋的专称。',
    hasForceAnim: false,
  },
  {
    id: 'sandou-8', name: '散斗·慢栱左', term: '散斗', pinyin: 'sǎndǒu',
    dims: { fang: 16, height: 10, ear: 4, ping: 2, xie: 4, kouWidth: 6, singleKou: true },
    juansha: null, layer: 6.55, parents: ['mangong'],
    role: '坐于慢栱左端栱头，与右端散斗一同承其上的罗汉枋。',
    desc: '散斗对称置于慢栱两端，斗口向上，共承罗汉枋。左右散斗把罗汉枋的重量分落到慢栱两端。',
    trivia: '一朵之中散斗前后共有数处：泥道栱端、瓜子栱端、慢栱端、令栱端——凡真横栱两端皆以散斗承上。',
    hasForceAnim: false,
  },
  {
    id: 'luohanfang', name: '罗汉枋', term: '罗汉枋', pinyin: 'luóhànfāng',
    dims: { length: 120, caiGuang: 15, houDou: 10 },
    juansha: null, layer: 6.6, parents: ['sandou-7', 'sandou-8'],
    role: '压在慢栱之上、沿墙面通长的联系枋，把相邻各朵斗栱在第二跳计心处连成一气。',
    desc: '罗汉枋是计心重栱之上的通长枋木，坐于慢栱两端散斗上，沿墙面横陈。它与泥道一列的柱头枋平行、在外一跳，是唐构计心层里联系相邻铺作的横向构件。',
    trivia: '罗汉枋因位在柱头枋之外、层层「罗列」而得名；它的出现正是第二跳「计心」的标志，也是佛光寺非全偷心的实据。',
    hasForceAnim: false,
  },
  {
    id: 'xiaang-1', name: '下昂·第一昂', term: '下昂', pinyin: 'xiàáng',
    dims: { length: 82, caiGuang: 21, houDou: 10, chuTiao: 30, slopeDeg: 25, lap: { side: 'bottom', width: 10, depth: 7, at: -8 } },
    juansha: null, layer: 7, parents: ['jiaohudou-2'],
    role: '下斜悬挑的杠杆：昂尖向外下伸承挑檐，昂尾向内上翘被屋架压住，以栌斗一线为支点平衡。',
    desc: '下昂是一根斜置长木，昂身自内向外下斜。它是斗栱中最精妙的杠杆构件：外挑之檐与内压之屋架各据支点两端，以巧妙的力学平衡出深远的屋檐。',
    trivia: '正是下昂的杠杆，让唐代大殿得以出檐深远如翼——佛光寺东大殿檐出近四米，却轻盈欲飞。',
    hasForceAnim: true,
  },
  {
    id: 'jiaohudou-3', name: '交互斗·承二昂', term: '交互斗', pinyin: 'jiāohùdǒu',
    dims: { fang: 18, height: 10, ear: 4, ping: 2, xie: 4, kouWidth: 8 },
    juansha: null, layer: 8, parents: ['xiaang-1'],
    role: '坐于第一下昂跳头，承接叠于其上的第二下昂，衔接双下昂之间的一跳。',
    desc: '此交互斗落在第一下昂挑出的跳头上，斗口朝上纳住第二下昂。双下昂并非直接相叠，而是各以跳头交互斗坐实，逐层把承檐点推得更外更高。',
    trivia: '双下昂之间的这颗交互斗，决定了两昂的出跳间距与举高节奏，是控制唐构舒展屋面曲线的隐形关节。',
    hasForceAnim: false,
  },
  {
    id: 'xiaang-2', name: '下昂·第二昂', term: '下昂', pinyin: 'xiàáng',
    dims: { length: 90, caiGuang: 21, houDou: 10, chuTiao: 30, slopeDeg: 25, lap: { side: 'bottom', width: 10, depth: 7, at: -8 } },
    juansha: null, layer: 9, parents: ['jiaohudou-3'],
    role: '第二重下昂，进一步出跳并抬高承檐点。',
    desc: '第二下昂叠于第一昂之上，再出一跳，将撩檐槫的承点推向更外更高处，形成双下昂的深远挑檐。',
    trivia: '双下昂逐层加大出挑与举高，是控制屋面举折、塑造唐构舒展屋顶曲线的关键。',
    hasForceAnim: false,
  },
  {
    id: 'jiaohudou-4', name: '交互斗·承耍头', term: '交互斗', pinyin: 'jiāohùdǒu',
    dims: { fang: 18, height: 10, ear: 4, ping: 2, xie: 4, kouWidth: 8 },
    juansha: null, layer: 10, parents: ['xiaang-2'],
    role: '坐于第二下昂昂头，承接其上顺出的耍头，是出跳收束处的最后一颗坐斗。',
    desc: '此交互斗落在第二下昂的昂头上，斗口朝上纳住顺昂而出的耍头。至此出跳到头，力的方向即将由斜挑的昂转回横置的令栱。',
    trivia: '昂头这颗交互斗是全朵最外、最高的一颗小斗，屋檐最外一道檩木的重量正是从这里开始，沿昂、栱、斗层层落回柱头。',
    hasForceAnim: false,
  },
  {
    id: 'shuatou', name: '耍头', term: '耍头', pinyin: 'shuǎtóu',
    dims: { length: 78, caiGuang: 21, houDou: 10, slopeDeg: 6, lap: { side: 'bottom', width: 10, depth: 7, at: -6 } },
    juansha: null, layer: 11, parents: ['jiaohudou-4'],
    role: '顺第二下昂之势向外挑出的收头构件，其上承令栱，是外跳最末露头的一件。',
    desc: '耍头顺昂而出、略呈批竹昂形，是铺作最外一挑的"露头"。它压在昂上、承其上的令栱，把出跳的势收在这一件里。佛光寺耍头断面为足材，与昂同厚。',
    trivia: '耍头露在檐下最外，形制最惹眼——批竹、蚂蚱头、麻叶头各代不同，是断代的一处好线索；佛光寺耍头朴劲近批竹，一派唐风。',
    hasForceAnim: false,
  },
  {
    id: 'linggong', name: '令栱', term: '令栱', pinyin: 'línggǒng',
    dims: { length: 72, caiGuang: 15, houDou: 10 },
    juansha: 5, layer: 12, parents: ['shuatou'],
    role: '最上横栱，横置于耍头之上承替木与撩檐槫，把檐槫之力横向摊给下方昂、栱。',
    desc: '令栱是铺作最上、也是外跳唯一「计心」的横栱，单材造，栱头卷杀五瓣，沿进深方向横陈，其上承替木以托撩檐槫。',
    trivia: '偷心造全朵只此一处出横栱——令栱之下诸跳皆偷心，唯到承檐这一跳才「计心」施令栱，可谓惜栱如金。',
    hasForceAnim: false,
  },
  {
    id: 'sandou-3', name: '散斗·令右', term: '散斗', pinyin: 'sǎndǒu',
    dims: { fang: 16, height: 10, ear: 4, ping: 2, xie: 4, kouWidth: 6, singleKou: true },
    juansha: null, layer: 12.3, parents: ['linggong'],
    role: '坐于令栱右端栱头，与左端散斗一同承托其上的替木。',
    desc: '散斗置于令栱右端栱头，斗口向上。替木不直接压在栱背，而是搁在这一对散斗上——散斗把替木、乃至撩檐槫的重量分落到令栱两端。',
    trivia: '令栱两端置散斗可确认；栱心是否另施一枚齐心斗，唐构实测尚无定论，此复原暂省而存疑，不作定说。',
    hasForceAnim: false,
  },
  {
    id: 'sandou-4', name: '散斗·令左', term: '散斗', pinyin: 'sǎndǒu',
    dims: { fang: 16, height: 10, ear: 4, ping: 2, xie: 4, kouWidth: 6, singleKou: true },
    juansha: null, layer: 12.6, parents: ['linggong'],
    role: '坐于令栱左端栱头，与右端散斗一同承托其上的替木。',
    desc: '散斗对称置于令栱两端，斗口向上，共承替木。左右两散斗把替木的重量分落到令栱的两个栱头上，令栱不致被一点压伤。',
    trivia: '一栱两端各一散斗，正是横栱之上标准的坐斗——先有散斗承接，才轮到替木、圆槫层层压上。',
    hasForceAnim: false,
  },
  {
    id: 'timu', name: '替木', term: '替木', pinyin: 'tìmù',
    dims: { length: 96, caiGuang: 12, houDou: 10, saddleRadius: 10, saddleSink: 4 },
    juansha: null, layer: 13, parents: ['sandou-3', 'sandou-4'],
    role: '压在令栱上的短枋，托住其上的撩檐槫，分散槫木对令栱的压力、增大接触。',
    desc: '替木是承槫之下的一段短木，沿进深方向横置于令栱之上。它像一块垫木，把圆槫的线接触摊成面接触，令栱不致被檩木压出凹痕。',
    trivia: '替木虽不起眼，却是圆槫与方栱之间的"缓冲"——有它，一根圆檩才能稳稳搁在栱头而不滚动、不压伤。',
    hasForceAnim: false,
  },
  {
    id: 'liaoyantuan', name: '橑檐槫', term: '橑檐槫', pinyin: 'liáoyántuán',
    dims: { length: 150, radius: 9 },
    juansha: null, layer: 14, parents: ['timu'],
    role: '最外一道屋檐檩木，承椽头、定檐口，是整朵斗栱层层上托所要撑住的最终对象。',
    desc: '橑檐槫是屋檐最外的一根圆檩，沿进深方向通长搁在替木上。屋檐的椽子搭在它上、由它定出檐口的位置与曲线——斗栱千挑万承，托的正是这一根槫。',
    trivia: '一朵斗栱的全部机巧，最终都为把这根橑檐槫稳稳撑到远离柱身的高处——檐出愈远，槫的位置愈外，斗栱便愈要层层出跳。',
    hasForceAnim: false,
  },
]

export function getPart(id) {
  return PARTS.find(p => p.id === id) || null
}
